name: .NET Continuous Integration

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run .NET CI Action
        uses: jmsudar/dotnet-continuous-integration@main
